### ISSUE TITLE
ioredis connection error

### ISSUE THREAD

**Issue by ademets** [HeliosOrg/SimpleDataIntegrationServer#1]
Trying to run the server, I get following error:
`[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379`
`at Object.exports._errnoException (util.js:1012:11)`
`at exports._exceptionWithHostPort (util.js:1035:20)`
`at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)`

I'm running the server from localhost (input.json has `http://localhost` as address). Tried it under Windows, as well as Ubuntu and got the same error.

**Comment by masterofshapes** [comment]
I have the same error did you have any luck?
