### ISSUE TITLE
[ioRedis] Error

### ISSUE THREAD

**Issue by masterofshapes** [HeliosOrg/SimpleDataIntegrationServer#2]
Following the server setup instructions. Everything goes great till I try and run the "node server.js" I get the following error:
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
at Object.exports._errnoException (util.js:870:11)
at exports._exceptionWithHostPort (util.js:893:20)
at TCPConnectWrap.afterConnect as oncomplete

Tried on both windows and ubuntu aws instance. Security rules on AWS is allowing access on port 80, and I disabled any firewall when I tried on windows.

**Comment by ttangGC** [comment]
I'm having a similar issue. When I change the port number to 8080 in server.js, I get this error:

> [ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND localhost localhost:6379
>     at errnoException (dns.js:26:10)
>     at GetAddrInfoReqWrap.onlookup [as oncomplete](dns.js:77:26)

**Comment by DennisAXu** [comment]
@ttangGC @masterofshapes can you guys try running redis-server before node server.js? Let me know if that helps.
